FROM python:3.11-slim

WORKDIR /app

# Instala dependencias del sistema necesarias para psycopg2
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

# gunicorn sirve la app Flask en producción; app:app -> archivo app.py, variable app
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
